# Generated by Django 5.2.1 on 2025-06-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_user_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='arrive_status',
            field=models.CharField(choices=[('Arrived', 'Arrived'), ('Not Arrived', 'Not Arrived')], default='Not Arrived', max_length=30),
        ),
        migrations.AddField(
            model_name='cart',
            name='confirmed_status',
            field=models.CharField(choices=[('Not Confirmed', 'Not Confirmed'), ('Confirmed', 'Confirmed')], default='Not Confirmed', max_length=30),
        ),
        migrations.AddField(
            model_name='cart',
            name='purchase',
            field=models.CharField(choices=[('Purchased', 'Purchased'), ('Not Purchased', 'Not Purchased')], default='Not Purchased', max_length=30),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('History', 'History')], default='In progress', max_length=20),
        ),
    ]
