# Generated by Django 5.2.1 on 2025-06-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
