# Generated by Django 5.2.1 on 2025-06-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_order_total_price_cartitems_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='arrive_status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='confirmed_status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='purchase',
        ),
    ]
