# Generated by Django 5.2.1 on 2025-06-07 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0008_remove_cart_arrive_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('choices', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=30)),
                ('confirmed_status', models.CharField(choices=[('Not Confirmed', 'Not Confirmed'), ('Confirmed', 'Confirmed')], default='Not Confirmed', max_length=30)),
                ('purchase', models.CharField(choices=[('Purchased', 'Purchased'), ('Not Purchased', 'Not Purchased')], default='Not Purchased', max_length=30)),
                ('arrive_status', models.CharField(choices=[('Arrived', 'Arrived'), ('Not Arrived', 'Not Arrived')], default='Not Arrived', max_length=30)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
