# Generated by Django 5.1.7 on 2025-05-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.PositiveIntegerField(blank=True, max_length=12, null=True),
        ),
    ]
