# Generated by Django 5.2.1 on 2025-06-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courier',
            field=models.BooleanField(default=False),
        ),
    ]
