# Generated by Django 5.2.1 on 2025-07-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_address_alter_customuser_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
