# Generated by Django 5.2.1 on 2025-05-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
