# Generated by Django 5.2.1 on 2025-06-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_meal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='type',
            field=models.CharField(choices=[('Trending', 'Trending'), ('Default', 'Default'), ('New', 'New')], default='Default', max_length=30),
        ),
    ]
