# Generated by Django 5.2.1 on 2025-06-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_meal_created_at_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.CharField(choices=[('Trending', 'Trending'), ('New', 'New'), ('Default', 'Default')], default='Default', max_length=30),
        ),
    ]
