# Generated by Django 5.2.1 on 2025-06-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_meal_stock_alter_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
