# Generated by Django 5.2.1 on 2025-06-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_meal_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='progress_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.CharField(choices=[('Default', 'Default'), ('Trending', 'Trending'), ('New', 'New')], default='Default', max_length=30),
        ),
    ]
