# Generated by Django 5.2.1 on 2025-06-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.CharField(choices=[('Trending', 'Trending'), ('Default', 'Default'), ('New', 'New')], default='Default', max_length=30),
        ),
    ]
