# Generated by Django 5.2.1 on 2025-06-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.CharField(choices=[('New', 'New'), ('Trending', 'Trending'), ('Default', 'Default')], default='Default', max_length=30),
        ),
    ]
