# Generated by Django 5.2.1 on 2025-06-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_alter_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.CharField(choices=[('Trending', 'Trending'), ('New', 'New'), ('Default', 'Default')], default='Default', max_length=30),
        ),
    ]
