# Generated by Django 5.2.1 on 2025-06-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_alter_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.CharField(choices=[('Default', 'Default'), ('Trending', 'Trending'), ('New', 'New')], default='Default', max_length=30),
        ),
    ]
