# Generated by Django 5.2.1 on 2025-06-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_alter_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.CharField(choices=[('New', 'New'), ('Default', 'Default'), ('Trending', 'Trending')], default='Default', max_length=30),
        ),
    ]
