# Generated by Django 5.2.1 on 2025-07-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_alter_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='media',
            field=models.ImageField(upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='media',
            field=models.ImageField(upload_to='meal/'),
        ),
    ]
