# Generated by Django 5.2.1 on 2025-07-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_alter_category_media_alter_meal_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.CharField(choices=[('Trending', 'Trending'), ('Default', 'Default'), ('New', 'New')], default='Default', max_length=30),
        ),
    ]
