# Generated by Django 5.2.1 on 2025-06-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Is Taken', 'Is Taken'), ('Queue', 'Queue')], max_length=40),
        ),
    ]
