# Generated by Django 5.2.1 on 2025-06-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_finished',
            field=models.CharField(choices=[('Finished', 'Finished'), ('Not Finished', 'Not Finished')], default='Not Finished', max_length=40),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Is Taken', 'Is Taken'), ('Queue', 'Queue')], default='Queue', max_length=40),
        ),
    ]
