# Generated by Django 5.2.1 on 2025-06-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_request_is_taken_alter_request_courier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='request',
            name='is_taken',
        ),
    ]
